package com.api.estoque.model;

public enum DashboardWidget {
    TOTAL_USUARIOS_ATIVOS,
    SOLICITACOES_PENDENTES,
    SOLICITACOES_APROVADAS_HOJE,
    TOTAL_EQUIPAMENTOS_EM_USO,
    TOTAL_EQUIPAMENTOS_CADASTRADOS,
    SOLICITACOES_FINALIZADAS_MES,
    SOLICITACOES_TOTAIS,
    EQUIPAMENTOS_ATIVOS,
    TOTAL_CATEGORIAS
}